# Generated by Django 4.2.1 on 2023-05-03 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('createddate', models.DateField(auto_now=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('Likeid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
                ('Postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app.post')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='app.user')),
            ],
        ),
    ]
