# Generated by Django 4.1.7 on 2023-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercartmodel',
            name='products',
            field=models.ManyToManyField(related_name='UserCartProductModel', to='accounts.usercartproductmodel'),
        ),
    ]
