# Generated by Django 4.1.7 on 2023-02-24 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Unique_id', models.CharField(default=uuid.UUID('b99efaf0-570f-4d8d-8b21-c287680f71f1'), max_length=12, unique=True)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserModel', to='Product.productmainmodel')),
            ],
        ),
    ]
