# Generated by Django 4.1.7 on 2023-02-24 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Unique_id',
            field=models.CharField(default=uuid.UUID('366dc0a4-8b21-44ef-b28b-3a1bc83e84eb'), max_length=12, unique=True),
        ),
    ]
