# Generated by Django 4.1.7 on 2023-02-24 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_productmainmodel_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Unique_id',
            field=models.CharField(default=uuid.UUID('801421e7-68a5-421c-80b0-d5da07469939'), max_length=12, unique=True),
        ),
    ]
