# Generated by Django 4.1.7 on 2023-02-24 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_productmainmodel_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Unique_id',
            field=models.CharField(default=uuid.UUID('5f2fabc9-cd7c-483b-8f61-401029d06994'), max_length=12, unique=True),
        ),
    ]
